import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.LabelView;

 /* @author Mthobisi
 */
public class New extends javax.swing.JFrame
{
        Connection conn;
        PreparedStatement ps;
        ResultSet rs;
        
        
        
    public New() {
        initComponents();
        try
        {
             Class.forName("com.mysql.cj.jdbc.Driver");
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
             System.out.println("Connected");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        //conn = (Connection) ConnectDB.Connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MoviesStrong2 = new javax.swing.JRadioButton();
        CheckBoxPap = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        CheckBoxOther = new javax.swing.JCheckBox();
        OutAgree = new javax.swing.JRadioButton();
        jSeparator7 = new javax.swing.JSeparator();
        RadioStrong = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        RadioStrongDis = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        OutDis = new javax.swing.JRadioButton();
        RadioDis = new javax.swing.JRadioButton();
        MoviesDis = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        OutNeutal = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        TextFullName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        OutStrongDis = new javax.swing.JRadioButton();
        bSubmit = new javax.swing.JButton();
        MoviesNeutral = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TvStrong = new javax.swing.JRadioButton();
        TvAgree = new javax.swing.JRadioButton();
        TvNeutral = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        TvStrongDis = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        TvDis = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        TextNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MoviesStrongDis = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        CheckBoxPizza = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        MoviesAgree = new javax.swing.JRadioButton();
        RadioAgree = new javax.swing.JRadioButton();
        CheckBoxPasta = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        OutStrong = new javax.swing.JRadioButton();
        RadioNeutral = new javax.swing.JRadioButton();
        TextNumber1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        bTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MoviesStrong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesStrong2ActionPerformed(evt);
            }
        });

        CheckBoxPap.setText("Pap and Wors");
        CheckBoxPap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxPapActionPerformed(evt);
            }
        });

        jLabel7.setText("Contact Number");

        CheckBoxOther.setText("Other");
        CheckBoxOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxOtherActionPerformed(evt);
            }
        });

        OutAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutAgreeActionPerformed(evt);
            }
        });

        RadioStrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioStrongActionPerformed(evt);
            }
        });

        jLabel10.setText("Please rate your level of agreement on a scale from 1 to 5, with 1 being \"strongly agree\" and 5 being \"strongly disagree\"");

        RadioStrongDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioStrongDisActionPerformed(evt);
            }
        });

        jLabel1.setText("_Surveys");

        OutDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutDisActionPerformed(evt);
            }
        });

        MoviesDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesDisActionPerformed(evt);
            }
        });

        jLabel11.setText("Wht is your favourite food?");

        jLabel15.setText("I like to eat out");

        OutNeutal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutNeutalActionPerformed(evt);
            }
        });

        jLabel16.setText("I like to watch movies");

        TextFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFullNameActionPerformed(evt);
            }
        });

        jLabel17.setText("I like to listen to radio");

        TextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEmailActionPerformed(evt);
            }
        });

        jLabel18.setText("I like to watch TV");

        OutStrongDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutStrongDisActionPerformed(evt);
            }
        });

        bSubmit.setText("SUBMIT");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        jLabel8.setText("Strongly Agree");

        jLabel9.setText("Agree");

        jLabel12.setText("Neutral");

        jLabel3.setText("FILL OUT SURVEY");

        jLabel13.setText("Disagree");

        TextNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNumberActionPerformed(evt);
            }
        });

        jLabel4.setText("Personal Details:");

        jLabel14.setText("Strongly Disagree");

        CheckBoxPizza.setText("Pizza");
        CheckBoxPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxPizzaActionPerformed(evt);
            }
        });

        jLabel5.setText("Full Names");

        MoviesAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesAgreeActionPerformed(evt);
            }
        });

        CheckBoxPasta.setText("Pasta");

        jLabel6.setText("Email");

        OutStrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutStrongActionPerformed(evt);
            }
        });

        jLabel19.setText("Age");

        bTest.setText("VIEW SURVEY RESULTS");
        bTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(237, 237, 237)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bTest))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TextNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6)
                                                    .addComponent(TextFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(CheckBoxPizza)
                                                        .addGap(31, 31, 31)
                                                        .addComponent(CheckBoxPasta)
                                                        .addGap(51, 51, 51)
                                                        .addComponent(CheckBoxPap))
                                                    .addComponent(jLabel19))
                                                .addGap(36, 36, 36)
                                                .addComponent(CheckBoxOther))
                                            .addComponent(TextNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addComponent(jSeparator7)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                                .addComponent(RadioStrong))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(OutStrong))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MoviesStrong2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TvStrong)))
                                        .addGap(74, 74, 74))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(46, 46, 46)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(RadioAgree)
                                    .addComponent(OutAgree)
                                    .addComponent(TvAgree)
                                    .addComponent(MoviesAgree))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(OutNeutal)
                                            .addComponent(RadioNeutral)
                                            .addComponent(TvNeutral)
                                            .addComponent(MoviesNeutral))))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RadioDis)
                                            .addComponent(OutDis)
                                            .addComponent(TvDis)
                                            .addComponent(MoviesDis))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(OutStrongDis)
                                            .addComponent(RadioStrongDis)
                                            .addComponent(TvStrongDis)
                                            .addComponent(MoviesStrongDis))
                                        .addGap(28, 28, 28))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(bSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(bTest))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CheckBoxPizza)
                    .addComponent(CheckBoxPasta)
                    .addComponent(CheckBoxPap)
                    .addComponent(CheckBoxOther))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioStrongDis)
                            .addComponent(RadioDis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OutStrongDis)
                            .addComponent(OutDis))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TvDis))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TvStrongDis)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MoviesDis)
                            .addComponent(MoviesStrongDis))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RadioAgree)
                                .addComponent(RadioNeutral)
                                .addComponent(RadioStrong))
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(OutNeutal)
                                .addComponent(OutAgree)
                                .addComponent(OutStrong)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TvAgree)
                                .addComponent(TvNeutral)
                                .addComponent(TvStrong)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MoviesNeutral)
                                .addComponent(MoviesAgree)
                                .addComponent(MoviesStrong2))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSubmit)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MoviesStrong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesStrong2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoviesStrong2ActionPerformed

    private void CheckBoxOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxOtherActionPerformed

    private void OutAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutAgreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutAgreeActionPerformed

    private void RadioStrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioStrongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioStrongActionPerformed

    private void RadioStrongDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioStrongDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioStrongDisActionPerformed

    private void OutDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutDisActionPerformed

    private void MoviesDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoviesDisActionPerformed

    private void OutNeutalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutNeutalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutNeutalActionPerformed

    private void TextFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFullNameActionPerformed

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void OutStrongDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutStrongDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutStrongDisActionPerformed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        // TODO add your handling code here:

        if(TextFullName.getText().isEmpty() & TextEmail.getText().isEmpty() 
                & TextNumber.getText().isEmpty() & TextNumber1.getText().isEmpty()
                & !CheckBoxPizza.isSelected() & !CheckBoxPasta.isSelected() &
                !CheckBoxPap.isSelected() & !CheckBoxPap.isSelected() &
                !CheckBoxOther.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Make sure all fields are filled and boxes checked");
        }
        if(RadioStrong.isSelected())
        {
            RadioAgree.setSelected(false);
            RadioNeutral.setSelected(false);
            RadioDis.setSelected(false);
            RadioStrongDis.setSelected(false);
            
        }
        else 
        {
            String sql ="INSERT INTO DAIRY(FullName,Email,Phone)VALUES(?,?,?)";
         try
        {
            //Class.forName("com.mysql.cj.jdbc.Driver");
            //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            //System.out.println("Connected");
            
            
            ps = conn.prepareStatement(sql);
            
            ps.setString(1, TextFullName.getText());
            ps.setString(2,TextEmail.getText() );
            
            
            JOptionPane.showMessageDialog(null, "Submited");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
          try
        {
            double number = Double.parseDouble(TextNumber.getText());
            
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(null,"Invalied Input. Please enter a number");
        }
       try
        {
             int age = Integer.parseInt(TextNumber1.getText());
             while(age <= 5 )
             {
                 JOptionPane.showMessageDialog(null, age + "year old can not participate only 6 year old and above");
             }
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(null,"Invalied Input. Please enter age");
        }

        }
         JOptionPane.showMessageDialog(null,"Submitted");      
    }//GEN-LAST:event_bSubmitActionPerformed

    private void CheckBoxPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxPizzaActionPerformed
        // TODO add your handling code here:
       /* String SelectedValue="";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            PreparedStatement ps = conn.prepareStatement("insert into infor (name,email, date, num) value('"+name+"','"+email+"')");
            
            StringBuilder selectedVaue = new StringBuilder();
            System.out.println("Successful insertion" + name);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Connection Error" + ex);
        }*/
        
    }//GEN-LAST:event_CheckBoxPizzaActionPerformed

    private void MoviesAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesAgreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoviesAgreeActionPerformed

    private void OutStrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutStrongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutStrongActionPerformed

    private void TextNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumberActionPerformed

    private void CheckBoxPapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxPapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxPapActionPerformed

    private void bTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTestActionPerformed
        // TODO add your handling code here:
        //Connection conn = null;
       new2 n = new new2();
       n.setVisible(true);
        

    }//GEN-LAST:event_bTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
              
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxOther;
    private javax.swing.JCheckBox CheckBoxPap;
    private javax.swing.JCheckBox CheckBoxPasta;
    private javax.swing.JCheckBox CheckBoxPizza;
    private javax.swing.JRadioButton MoviesAgree;
    private javax.swing.JRadioButton MoviesDis;
    private javax.swing.JRadioButton MoviesNeutral;
    private javax.swing.JRadioButton MoviesStrong2;
    private javax.swing.JRadioButton MoviesStrongDis;
    private javax.swing.JRadioButton OutAgree;
    private javax.swing.JRadioButton OutDis;
    private javax.swing.JRadioButton OutNeutal;
    private javax.swing.JRadioButton OutStrong;
    private javax.swing.JRadioButton OutStrongDis;
    private javax.swing.JRadioButton RadioAgree;
    private javax.swing.JRadioButton RadioDis;
    private javax.swing.JRadioButton RadioNeutral;
    private javax.swing.JRadioButton RadioStrong;
    private javax.swing.JRadioButton RadioStrongDis;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextFullName;
    private javax.swing.JTextField TextNumber;
    private javax.swing.JTextField TextNumber1;
    private javax.swing.JRadioButton TvAgree;
    private javax.swing.JRadioButton TvDis;
    private javax.swing.JRadioButton TvNeutral;
    private javax.swing.JRadioButton TvStrong;
    private javax.swing.JRadioButton TvStrongDis;
    private javax.swing.JButton bSubmit;
    private javax.swing.JButton bTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
